<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>PCOptimizer</AssemblyName>
    <ApplicationIcon></ApplicationIcon>

    <!-- Tek dosya (single exe) yayın ayarları -->
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <PublishReadyToRun>false</PublishReadyToRun>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>

    <!-- Uygulama yönetici (admin) olarak çalışsın, registry/servis değiştirebilsin -->
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

</Project>
